logging.file: logs/application.log
logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: ERROR
spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:file:./h2/db
    driver-class-name: org.h2.Driver
    database-platform: org.hibernate.dialect.H2Dialect
    username: root
    password: 123456
    jpa:
    properties.hibernate.hbm2ddl.auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2